package errors;

public enum ErrorType {
    SEMICOLON_AFTER_IF,
    BITWISE_OPERATOR,
    NOT_USING_EQUALS,
    IGNORING_RETURN_VALUE,
    STATIC_AS_NORMAL,
    IF_WITHOUT_BRACKETS,
    NOT_IMPLEMENTING_EQUALS,
    FIELD_DECL_NO_INIT
}